{
 "Revision": 1,
 "Etcd": {
  "Endpoints": [
   "localhost:2379"
  ],
  "Timeout": 5
 },
 "Server": {
  "Keepalive": 10,
  "Insecure": false,
  "Mtu": 1300
 },
 "Crypto": {
  "Type": "gcm",
  "Key": "6368616e676520746869732070617373776f726420746f206120736563726574"
 },
 "Nodes": [
  {
   "Node": {
    "Name": "node1",
    "Address": "192.168.0.19",
    "PrivateAddresses": [
     "10.110.0.4/24"
    ],
    "PrivateSubnets": [
     "10.110.0.0/24"
    ]
   }
  }
 ]
}